// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;

        public PlayerDataServiceBindings() : this(CloudCodeService.Instance) { }

        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<TempleRunUGSCloud.Models.PlayerInitializationResponse> OnSignInHandlePlayerInitialization()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerInitializationResponse>(
                "TempleRunUGSCloud",
                "OnSignInHandlePlayerInitialization",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<TempleRunUGSCloud.Models.PlayerDataSyncResponse> SyncAllPlayerData()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerDataSyncResponse>(
                "TempleRunUGSCloud",
                "SyncAllPlayerData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<TempleRunUGSCloud.Models.PlayerData> GetPlayerData()
        {
            return await k_Service.CallModuleEndpointAsync<TempleRunUGSCloud.Models.PlayerData>(
                "TempleRunUGSCloud",
                "GetPlayerData",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
